[versions]

[libraries]
archunit-junit5 = { module = "com.tngtech.archunit:archunit-junit5", version = "1.0.0-rc1" }

jakarta-persistence-api = {module="jakarta.persistence:jakarta.persistence-api", version="2.2.3"}
jakarta-validation-api = {module="jakarta.validation:jakarta.validation-api", version="2.0.2"}

[bundles]

[plugins]
autoconfigure = { id = "io.cloudflight.autoconfigure-gradle", version = "0.5.3" }
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version = "1.1.0" }

